### ISSUE TITLE
Posh-HP thoughts?

### ISSUE THREAD

**Issue by jscooksey** [Nevets82/Posh-Cisco#4]
Any plans to work on a Posh-HP variant to get backups of HP ProCurve Switches?

**Comment by alagoutte** [comment]
for Procurve (ArubaOS) Switches, it will be better (more easy) to use REST API !

**Comment by Nevets82** [comment]
No, not at the moment. Mainly because I do not have access to HP ProCurve switches. You can use this project as a base if you want.
